project:
  type: website

website:
  site-url: "https://bits2nats.rajpatil.dev"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Author
      - href: https://rajpatil.dev/resume
        text: Résumé
    right:
      - icon: feather
        text: root site
        href: https://rajpatil.dev
      - icon: pencil-square
        text: brain-dump
        href: https://buffer.rajpatil.dev
      - icon: activity
        text: kaggle
        href: https://www.kaggle.com/rp152k
      - icon: github
        text: github
        href: https://github.com/
      - icon: twitter
        text: twitter
        href: https://twitter.com
      - icon: envelope-at-fill
        text: mail
        href: mailto:contact@rajpatil.dev
      - icon: yin-yang
        text: I know not ...
        href: https://rajpatil.dev/i-know-not/
  page-navigation: true
  page-footer: "Copyright 2023, Raj Patil"
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7
